server {
    listen 80;
    server_name yourdomain.com;

    location / {
        root /opt/ai/hermes-web-chat-mvp/frontend;
        index index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

	proxy_connect_timeout 60s;
    	proxy_send_timeout 300s;
    	proxy_read_timeout 300s;
    }

    error_log /var/log/openresty/hermes.error.log;
    access_log /var/log/openresty/hermes.access.log;
}
